---
apiVersion: v1
kind: Service
metadata:
  name: dwi67-test-flask-service
spec:
  type: ClusterIP
  selector:
    app: dwi67-test-app
    username: dwi67
    env: test
  ports:
  - name: dwi67-test-flask
    port: 5000
    targetPort: 5000
