---

 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: dwi67-test-pvc
   labels:
     username: dwi67
     env: test
 spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: cinder-csi
   resources:
     requests:
       storage: 1Gi
